config/routes.rb
RailStrap::Application.routes.draw do

  root :to => "users#home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  post "sessions" => "sessions#create"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :require_login
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	def require_login
		unless logged_in?
		  flash[:error] = "You must be logged in to access this section"
		  redirect_to log_in_url
		end
	end


	# The logged_in? method simply returns true if the user is logged
	# in and false otherwise. It does this by "booleanizing" the
	# current_user method we created previously using a double ! operator.
	# Note that this is not common in Ruby and is discouraged unless you
	# really mean to convert something into true or false.
	def logged_in?
		!!current_user
	end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      redirect_to root_url, :notice => "Invalid email or password"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create, :home]
  def new
    @user = User.new
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
      format.json{ render :json => @users }
    end
  end

  def show
    @user = User.find_by_id(params[:id])

    # If user not found
    if @user.nil?
      redirect_to users_path , :notice => "User not found"
    else
      respond_to do |format|
        format.html
        format.xml { render :xml  => @user }
        format.json{ render :json => @user }
      end
    end
  end
  

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
  
  def home
    @user = User.new
  end 

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user,
                      :notice => 'User updated')}
        format.json { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @user.errors,
                      :status => :unprocessable_entity }        
      end
    end
  end

  def destroy
    if current_user.id.to_s === params[:id].to_s
      redirect_to users_path, :notice => "You cant delete yourself !"
    else
      @user = User.find(params[:id])
      @user.delete      

      respond_to do |format|
        format.html { redirect_to users_path, :notice => 'User deleted' }
        format.json { head :no_content }
      end      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!-- Consider specifying the language of your content by adding the `lang` attribute to <html> -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailStrap v 0.1</title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag '__main.css' %>
    <%= stylesheet_link_tag '_bootstrap.min.css' %>
    <%= stylesheet_link_tag 'bootstrap-responsive.min.css' %>
    
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <%= javascript_include_tag 'modernizr-2.5.3.min.js' %>
    <%= javascript_include_tag "templates/all" %>

    <%= csrf_meta_tag %>
</head>
<body>
    <!--[if lt IE 7]><p class="chromeframe">Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to "RailStrap", root_path, :class => 'brand' %>

          <div class="nav-collapse">
            <ul class="nav">
              <% if current_user %>
              <li><%= link_to "Users", users_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
          <% if current_user %>
          <div class="nav-collapse pull-right">
            <ul class="nav">
              <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged as <%= current_user.email %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Log out", log_out_path %></li>
                </ul>
              </li>              
            </ul>
          </div>
          <% end %>       
        </div>
      </div>
    </div>

    <div class="container">

      <div class="row">
        <% flash.each do |name, msg| %>
          <div class="alert">
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>              
      </div>
      
      <%= yield %>

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/assets/jquery.min.js" type="text/javascript"><\/script>')</script>

    <!-- scripts concatenated and minified via build script -->
    <%= javascript_include_tag 'jquery_ujs.js' %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
    <%= javascript_include_tag 'application.js' %>
    <!-- end scripts -->

    <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
         mathiasbynens.be/notes/async-analytics-snippet -->
    <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_field :email, :placeholder => 'Email' %>
  </p>
  <p>
    <%= f.password_field :password, :placeholder => 'Password' %>
  </p>
  <p>
    <%= f.password_field :password_confirmation, :placeholder => 'Password confirm' %>
  </p>
  <p class="button"><%= f.submit :class => 'btn btn-success', :value => 'Register' %></p>
<% end %>

app/views/users/edit.html.erb
<h2>Edit user</h2>
<hr>
<%= render 'form' %>

app/views/users/home.html.erb
<div class="row">
	<div class="hero-unit">
		<div class="row-fluid">
			<div class="span8">

			<% if current_user %>
				<h3>Hello <%= current_user.email %></h3>
			<% else %>
				<h1> RailStrap v 0.1 </h1>
			<% end %>
			<hr>
			<% if current_user %>
				<h4><%= link_to "Manage users", users_path %></h4>
			<% else %>
			<h3>Features</h3>
			<ul>
				<li>
					<strong>Front-end</strong>
					<ul>
						<li> <i class="icon-ok"></i> <a href="http://html5boilerplate.com/" target="_blank">HTML5 Boilerplate</a> </li>
						<li> <i class="icon-ok"></i> <a href="http://twitter.github.com/bootstrap/" target="_blank"> Twitter Bootsrap 2.0</a> </li>
					</ul>
				</li>
				<li>
					<strong>Back-end</strong>
					<ul>
						<li> <i class="icon-ok"></i> <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a> 3.2.x</li>
						<li> <i class="icon-ok"></i> Authentication System</li>
					</ul>
				</li>
			</ul>
			<% end %>
			</div>
			<div class="span4">
				<% unless current_user %>
					<div class="tabbable">
					  <ul class="nav nav-tabs">
					    <li class="active"><a href="#tab1" data-toggle="tab">Log in</a></li>
					    <li><a href="#tab2" data-toggle="tab">Sign up</a></li>
					  </ul>
					  <div class="tab-content">
					    <div class="tab-pane active" id="tab1">
					      <%= render "sessions/form" %>
					    </div>
					    <div class="tab-pane" id="tab2">
					      <%= render :partial => "form", :locals => { :user => @user } %>
					    </div>
					  </div>
					</div>
				<% end %>
				
			</div>		

		</div>

		
		
	</div>
</div>

app/views/users/index.html.erb
<h2>Users</h2>
<hr>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>#</th>
			<th>Email</th>
			<th>#</th>
			<th>#</th>
			<th>#</th>
		</tr>
	</thead>
	<tbody>
	<% @users.each do |user| %>
		<tr>
			<td><%= user.id %></td>
			<td><%= user.email %></td>
			<td><%= link_to "Show", user %></td>
			<td><%= link_to "Edit", edit_user_path(user) %></td>
			<td><%= link_to "Delete", user, :confirm => "Are you sure?", :method => :delete %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<div class="row">
  <div class="hero-unit">
		<h2>Sign Up</h2>
 	 	<hr> 		  	
    <%= render :partial => "form", :locals => { :user => @user } %>
  </div>
</div>

app/views/users/show.html.erb
<h2>User</h2>
<hr>
Email: <%= @user.email %>